language: node_js
node_js:
  - '8.9.4'
before_script:
  - npm install grunt-cli -g
  - npm install codecov -g
script:
  - npm test
  - npm run codecov
  - npm run build:all
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_deploy:
  - git config --global user.email "maxgug@hotmail.com"
  - git config --global user.name "koalyptus"
  - export GIT_TAG=$(git describe --tags --abbrev=0)
  - echo -n $GIT_TAG
  - export NEW_GIT_TAG=$(node -p -e "require('./package.json').version")
  - echo -n $NEW_GIT_TAG
  - |
    if [ $GIT_TAG != $NEW_GIT_TAG ]; then
      git tag $NEW_GIT_TAG -am "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
    fi
deploy:
  - provider: releases
    on:
      branch: master
    api_key: $GITHUB_OAUTH_ACCESS_TOKEN
    skip_cleanup: true
    name: $NEW_GIT_TAG
  - provider: s3
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: www.tablefilter.com
    skip_cleanup: true
    local_dir: dist
  - provider: s3
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: www.tablefilter.com
    skip_cleanup: true
    local_dir: docs
env:
  global:
  - secure: A1G8GvJkV0rjy7XCTVdOpTHy3xaoSZZAbMWhI+ikrqBqd8mRz+sB71FhRusouTcYdsT5VfF9Io2doS8LKAeP0TNC34Pp0uvjtsvarzn8a/oNEOuqR3Ub0ws2bmbZIZc+wOpgErKOj1H1QSJAUpd6ZjIuEAbOVXlhGBJz3zUCmcpRDh32CpFKC62oFWeGlvttxPciLLzBfKgkVKEGhPtdGP/xCHL1MCQptYVHZiXwWsaIQ5wHFO6KCVlRrPgdfOL+Yce3mT02iXH6ZjW6U6zA6vYQVQZVD873AkU5RmirYblW+jW1wdvu4UXI71lSH6Z3uXRVnrw1b0TsLVTjP9ZUbCtkTHtLbxYzeDjEukxKoCjpAppIhOtaNIxrdA8oKJAabQYp5X+QK6lkosy0zdT5u2B1+g8unZhsf0y//7lgLUe04iQ7sc1Q6AHiiEGtByaXg4BHNW53bUfKgNnbV4+IbXf8rz5wWOxL2/yWAU/GoiszjqRQfajAXCpSf6SyMjXjhhvQdeFn+Cz6FwdtaxH+tOIY0Hq9Gqy1xrLIkv/httd3O+AbhLrU1c/M0MwlFQue7GeJb7ZyF3KsK7bXvoz2dEqvzHd98NZXiQEqFXCIs77uVh4eZMoYrbEyrkOAgkUZNQYhHh9fuvfynJ/zgUvyA0v3GUvBebq3ybYKD/vqX7s=
